
services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    env_file:
      - .env
  celery:
    build: ./backend
    command: celery -A app.celery worker --loglevel=info
    env_file:
      - .env

  celery-beat:
    build: ./backend
    command: celery -A app.celery beat --loglevel=info
    env_file:
      - .env